sh_default_service: "workspace"
sh_always_admin: false
build_default_containers:
- workspace
- php-fpm
- nginx
- mysql
up_default_containers:
- workspace
- nginx
- mysql
watch_configs:
  service: ""
  command: ""
  args: []
