sh_default_service: "workspace"
sh_always_admin: true
build_default_containers:
  - pgadmin
  - php-fpm
  - php-worker
  - nginx
  - postgres
  - workspace
  - redis
  - mongo
  - mongo-webui
  - docker-in-docker
up_default_containers:
  - pgadmin
  - php-fpm
  - nginx
  - postgres
  - workspace
  - redis
  - mongo
  - docker-in-docker
watch_configs:
  service: ""
  command: ""
  args: []
